-   id: perlcritic
    name: 'perlcritic'
    entry: run-perlcritic.sh
    files: '\.(pl|pm|t|PL)$'
    language: 'script'
    description: "Runs `perlcritic`, requires script in PATH"
-   id: perltidy
    name: 'perltidy'
    entry: run-perltidy.sh
    args: [--min-version=20021130]
    files: '\.(pl|pm|t|PL)$'
    language: 'script'
    description: "Runs `perltidy`, requires script in PATH"
