-   id: perlcritic
    name: 'perlcritic'
    entry: run-perlcritic.sh
    files: '\.(pl|pm|t|PL)$'
    language: 'script'
    description: "Runs `perlcritic`, requires script in PATH"
-   id: perltidy
    name: 'perltidy'
    entry: run-perltidy.sh
    files: '\.(pl|pm|t|PL)$'
    language: 'script'
    description: "Runs `perltidy`, requires script in PATH"
-   id: perlimports
    name: 'perlimports'
    entry: run-perlimports.sh --inplace-edit
    files: '\.(pl|pm|t|PL)$'
    language: 'script'
    description: "Runs `perlimports --inplace-edit`, requires script in PATH"
-   id: perlimports-lint
    name: 'perlimports-lint'
    entry: run-perlimports.sh --lint
    files: '\.(pl|pm|t|PL)$'
    language: 'script'
    description: "Runs `perlimports --lint`, requires script in PATH"
